// Полные данные о всех районах Беларуси
const districtsInfo = {
    // ===== БРЕСТСКАЙ =====
    "Брестский": {
        name: "Брестский",
        region: "Брестская",
        center: "Брест",
        centerCoords: [23.69, 52.09],
        population: "248,500",
        area: "2,128 км²",
        density: "116.8",
        founded: 1019,
        foundedDescription: "Один из древнейших городов Беларуси.",
        landmarks: ["Брестская крепост", "Музей Берестье"],
        economy: ["Машиностроение", "Логистика"],
        description: "Административный и культурный центр области."
    },
    "Барановичский": {
        name: "Барановичский",
        region: "Брестская",
        center: "Барановичи",
        centerCoords: [26.01, 53.13],
        population: "193,800",
        area: "1,869 км²",
        density: "103.7",
        founded: 1871,
        foundedDescription: "Основан как железнодорожная станция.",
        landmarks: ["Николаевская церковь"],
        economy: ["Машиностроение", "Транспорт"],
        description: "Важный железнодорожный узел."
    },
    "Пинский": {
        name: "Пинский",
        region: "Брестская",
        center: "Пинск",
        centerCoords: [26.09, 52.12],
        population: "151,100",
        area: "1,645 км²",
        density: "91.8",
        founded: 1097,
        foundedDescription: "Древний город на Припяти.",
        landmarks: ["Костел Иезуитов"],
        economy: ["Деревообработка", "Химия"],
        description: "Приодные оважные достопримечательности."
    },
    "Кобринский": {
        name: "Кобринский",
        region: "Брестская",
        center: "Кобрин",
        centerCoords: [24.36, 52.21],
        population: "82,400",
        area: "1,245 км²",
        density: "66.2",
        founded: 1287,
        foundedDescription: "Город на Немане.",
        landmarks: ["Музей региональные"],
        economy: ["Сельское хозяйство"],
        description: "Приграничный город."
    },
    // ===== ГОМЕЛЬСКАЙ =====
    "Гомельский": {
        name: "Гомельский",
        region: "Гомельская",
        center: "Гомель",
        centerCoords: [30.98, 52.43],
        population: "486,300",
        area: "2,154 км²",
        density: "225.8",
        founded: 1142,
        foundedDescription: "Областной центр.",
        landmarks: ["Дворец Культуры"],
        economy: ["Нефтехимия", "Машиностроение"],
        description: "Крупный региональный центр."
    },
    "Мозырский": {
        name: "Мозырский",
        region: "Гомельская",
        center: "Мозырь",
        centerCoords: [29.25, 52.05],
        population: "132,800",
        area: "1,634 км²",
        density: "81.3",
        founded: 1155,
        foundedDescription: "Нефтехимический центр.",
        landmarks: ["Мужской монастырь"],
        economy: ["Нефтепереработка"],
        description: "Промышленный центр на Днепре."
    },
    "Речицкий": {
        name: "Речицкий",
        region: "Гомельская",
        center: "Речица",
        centerCoords: [30.39, 52.36],
        population: "94,800",
        area: "1,876 км²",
        density: "50.5",
        founded: 1213,
        foundedDescription: "Город на Днепре.",
        landmarks: ["Церковь"],
        economy: ["Химия", "сельское хозяйство"],
        description: "Исторический город."
    },
    // ===== ВИТЕБСКАЙ =====
    "Витебский": {
        name: "Витебский",
        region: "Витебская",
        center: "Витебск",
        centerCoords: [30.20, 55.19],
        population: "328,300",
        area: "2,834 км²",
        density: "115.8",
        founded: 974,
        foundedDescription: "Один из древнейших городов Европы.",
        landmarks: ["Софийский собор", "Гродовое овал"],
        economy: ["Нефтехимия", "ткани промышленность"],
        description: "Культурный центр с богатым наследием."
    },
    "Полоцкий": {
        name: "Полоцкий",
        region: "Витебская",
        center: "Полоцк",
        centerCoords: [28.78, 55.49],
        population: "93,500",
        area: "1,432 км²",
        density: "65.3",
        founded: 862,
        foundedDescription: "Древний книга монастырь.",
        landmarks: ["Софийский собор"],
        economy: ["Нефтехимия"],
        description: "центр русского освятителя."
    },
    // ===== МИНСКАЙ =====
    "Минский": {
        name: "Минский",
        region: "Минская",
        center: "Минск",
        centerCoords: [27.56, 53.9],
        population: "2,340,000",
        area: "2,156 км²",
        density: "1,085",
        founded: 1067,
        foundedDescription: "Национальная столица Республики.",
        landmarks: ["Национальная библиотека"],
        economy: ["ИТ", "Производство"],
        description: "Основное политическое и экономическое сердце страны."
    },
    "Борисовский": {
        name: "Борисовский",
        region: "Минская",
        center: "Борисов",
        centerCoords: [28.51, 54.23],
        population: "167,200",
        area: "1,823 км²",
        density: "91.7",
        founded: 1102,
        foundedDescription: "автомобильный центр.",
        landmarks: ["Музей ЛЭАВ"],
        economy: ["Автомобилестроение"],
        description: "Промышленный центр."
    },
    "Мядельский": {
        name: "Мядельский",
        region: "Минская",
        center: "Мядель",
        centerCoords: [27.15, 54.55],
        population: "33,200",
        area: "1,356 км²",
        density: "24.5",
        founded: 1495,
        foundedDescription: "Озерные районы.",
        landmarks: ["Озера Нарочь"],
        economy: ["Туризм"],
        description: "Природные достопримечательности."
    },
    // ===== ГРОДНЕНСКАЙ =====
    "Гродненский": {
        name: "Гродненский",
        region: "Гродненская",
        center: "Гродно",
        centerCoords: [23.83, 53.68],
        population: "267,800",
        area: "1,934 км²",
        density: "138.4",
        founded: 1128,
        foundedDescription: "Областные центр.",
        landmarks: ["Новый замок", "Старый замок"],
        economy: ["Химия", "Легкая промышленность"],
        description: "Приграничный туристический центр."
    },
    "Лидский": {
        name: "Лидский",
        region: "Гродненская",
        center: "Лида",
        centerCoords: [25.30, 53.88],
        population: "112,800",
        area: "1,645 км²",
        density: "68.6",
        founded: 1323,
        foundedDescription: "Медиевальный город с замком.",
        landmarks: ["Лидский замок"],
        economy: ["Машиностроение"],
        description: "Наявная замком."
    },
    // ===== МОГИЛЕВСКАЙ =====
    "Могилёвский": {
        name: "Могилёвский",
        region: "Могилёвская",
        center: "Могилёв",
        centerCoords: [30.33, 53.90],
        population: "315,600",
        area: "1,967 км²",
        density: "160.3",
        founded: 1267,
        foundedDescription: "Областные центр.",
        landmarks: ["Кафедральный собор"],
        economy: ["Машиностроение", "Химия"],
        description: "Областные культурные центр."
    },
    "Бобруйский": {
        name: "Бобруйский",
        region: "Могилёвская",
        center: "Бобруйск",
        centerCoords: [29.22, 53.14],
        population: "252,300",
        area: "1,678 км²",
        density: "150.3",
        founded: 1387,
        foundedDescription: "Промышленный центр.",
        landmarks: ["Крепость Бобруйска"],
        economy: ["Машиностроение"],
        description: "гисторические фортификации."
    }
};
